=== juvenal/test-case/scripts/testcase.dtd
<!ELEMENT testcase (docinfo, script, summary)>
<!ELEMENT docinfo (name, description, objectives, activities)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT objectives (entry)+>
<!ELEMENT entry (#PCDATA)>
<!ELEMENT activities (activity)+>
<!ELEMENT activity (id, description)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT script (feeds | commands | compare)+>
<!ELEMENT feeds (feed)+>
<!ELEMENT feed (activityid, pathname)>
<!ELEMENT activityid (#PCDATA)>
<!ELEMENT pathname (#PCDATA)>
<!ELEMENT commands (command)+>
<!ELEMENT command (parameters)>
<!ELEMENT base (#PCDATA)>
<!ELEMENT parameters (parameter)+>
<!ELEMENT parameter EMPTY>
<!ELEMENT compare (query | file)+>

<!ELEMENT query (joins*, conditions, validations)>
<!ELEMENT joins (join)+>
<!ELEMENT join (conditions)>
<!ELEMENT conditions (andblock | orblock | eq | ne | gt | ge | lt | le)>
<!ELEMENT andblock (andblock | orblock | eq | ne | gt | ge | lt | le)+>
<!ELEMENT orblock (orblock | andblock | eq | ne | gt | ge | lt | le)+>
<!ELEMENT validations (validation)+>
<!ELEMENT validation EMPTY>

<!ELEMENT file (name, checks)>
<!ELEMENT checks (check)+>
<!ELEMENT check (rectype*, super*, conditions, validations)>
<!ELEMENT super (rectype, super*, conditions)>
<!ELEMENT rectype (#PCDATA)>

<!ELEMENT summary (description)+>

<!ELEMENT eq EMPTY>
<!ELEMENT ne EMPTY>
<!ELEMENT gt EMPTY>
<!ELEMENT lt EMPTY>
<!ELEMENT ge EMPTY>
<!ELEMENT le EMPTY>

<!ATTLIST file
          type (columns|fields) "fields">
<!ATTLIST eq
          field CDATA #REQUIRED
          value CDATA #REQUIRED>
<!ATTLIST gt
          field CDATA #REQUIRED
          value CDATA #REQUIRED>
<!ATTLIST ge
          field CDATA #REQUIRED
          value CDATA #REQUIRED>
<!ATTLIST lt
          field CDATA #REQUIRED
          value CDATA #REQUIRED>
<!ATTLIST le
          field CDATA #REQUIRED
          value CDATA #REQUIRED>
<!ATTLIST ne
          field CDATA #REQUIRED
          value CDATA #REQUIRED>
<!ATTLIST validation
          field    CDATA #REQUIRED
          expected CDATA #REQUIRED>
<!ATTLIST command
          name CDATA #REQUIRED>
<!ATTLIST parameter
          key   CDATA #REQUIRED
          value CDATA #IMPLIED>
<!ATTLIST query
          table CDATA #REQUIRED>
<!ATTLIST join
          type  CDATA #IMPLIED
          table CDATA #REQUIRED>

=== juvenal/test-case/scripts/testcase.xml
<?xml version="1.0"?>
<!DOCTYPE testcase SYSTEM "testcase.dtd">
<testcase>
  <docinfo>
    <name>...</name>
    <description>...</description>
    <objectives>
      <entry>...</entry>
      <entry>...</entry>
      <entry>...</entry>
      <entry>...</entry>
    </objectives>
    <activities>
      <activity>
        <id>...</id>
        <description>...</description>
      </activity>
      <activity>
        <id>...</id>
        <description>...</description>
      </activity>
    </activities>
  </docinfo>
  <script>
    <feeds>
      <feed>
        <activityid>...</activityid>
        <pathname>TC751_F000</pathname>
      </feed>
      <feed>
        <activityid>...</activityid>
        <pathname>TC751_F001</pathname>
      </feed>
    </feeds>
    <commands>
      <command name="ansb_batch">
        <parameters>
          <parameter key="v"/>
          <parameter key="s" value="000000"/>
          <parameter key="e" value="999999"/>
        </parameters>
      </command>
    </commands>
    <compare>
      <query table="...">
        <conditions>
          <andblock>
            <eq item="..." value="..."/>
            <ne item="..." value="..."/>
            <lte item="..." value="..."/>
            <orblock>
              <gt item="..." value="..."/>
              <lt item="..." value="..."/>
            </orblock>
            <gte item="..." value="..."/>
          </andblock>
        </conditions>
        <validations>
          <validation field="..." expected="..."/>
          <validation field="..." expected="..."/>
        </validations>
      </query>
      <file type="columns">
        <name>...</name>
        <conditions>
          ...
        </conditions>
        <checks>
          ...
        </checks>
      </file>
      <file type="fields">
        <name>...</name>
        <conditions>
          ...
        </conditions>
        <checks>
          ...
        </checks>
      </file>
    </compare>
  </script>
  <summary>
    <description>...</description>
  </summary>
</testcase>
